version: '3.6'

services:
  back-end:
    image: registry2.bunnyinc.com/build/node:10.16.0-alpine
    ports:
      - "5000:5000" 
    volumes:
      - ./back-end:/data
    command: >
      sh -c "npm install && npm test" 
  front-end:
    image: registry2.bunnyinc.com/build/node:10.16.0-alpine
    ports:
      - "5050:5050" 
    volumes:
      - ./front-end:/data
    command: >
      sh -c "npm install && npm test"
 
 
    