version: '2'

services:
  back-end:
    image: 697826815912.dkr.ecr.us-east-1.amazonaws.com/ecr_bunnystudio_study_node:latest
    ports:
      - "5000:5000" 
    volumes:
      - ./back-end:/data
    command: npm start /data 
  front-end:
    image: 697826815912.dkr.ecr.us-east-1.amazonaws.com/ecr_bunnystudio_study_node:latest
    ports:
      - "5050:5050" 
    volumes:
      - ./front-end:/data
    command: npm start /data
  # jenkins:
  #   image: "registry2.bunnyinc.com/build/jenkins:2.189"
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/jenkins_home:/var/jenkins_home
  influxdb:
    image: "influxdb"
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - INFLUXDB_DB=jenkins
  grafana:
    image: "grafana/grafana:3.1.1"
    ports:
      - "3000:3000"
    links:
      - influxdb
    