version: '3.6'

services:
  back-end:
    image: 679035925558.dkr.ecr.us-west-2.amazonaws.com/ecr_bunnystudio_study_node:latest
    ports:
      - "5000:5000" 
    volumes:
      - ./back-end:/data
    command: >
      sh -c "npm install && npm test" 
  front-end:
    image: 679035925558.dkr.ecr.us-west-2.amazonaws.com/ecr_bunnystudio_study_node:latest
    ports:
      - "5050:5050" 
    volumes:
      - ./front-end:/data
    command: >
      sh -c "npm install && npm test"
 
 
    