version: '3.6'


services:
  back-end:
    image: registry2.bunnyinc.com/build/node:10.16.0-alpine
    ports:
      - "5000:5000" 
    volumes:
      - ./back-end:/data
    command: npm start /data 
  front-end:
    image: registry2.bunnyinc.com/build/node:10.16.0-alpine
    ports:
      - "5050:5050" 
    volumes:
      - ./front-end:/data
    command: npm start /data
  jenkins:
    image: "registry2.bunnyinc.com/build/jenkins:2.189"
    ports:
      - "8080:8080"
    links:
      - influxdb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/jenkins_home:/var/jenkins_home
  influxdb:
    image: "influxdb"
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - INFLUXDB_DB=jenkins
  grafana:
    image: "grafana/grafana:3.1.1"
    ports:
      - "3000:3000"
    links:
      - influxdb
    