version: '3.6'

services:
  back-end:
    image: inside_back
    ports:
      - "5000:5000" 
    command: >
      sh -c "npm install && cd src && mocha" 
  front-end:
    image: inside_front
    ports:
      - "5050:5050" 
    command: >
      sh -c "npm install && cd src && mocha"
 
 
    